sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t galoptival/react-docker-udemy -f Dockerfile.dev

script:
  - docker run -e CI=true galoptival/react-docker-udemy npm run test