FROM node:16-alpine
# USER node

# RUN mkdir -p /home/node/react_app
WORKDIR '/react_app'


COPY package.json .
# COPY --chown=node:node ./package.json ./

RUN npm install
# RUN npm build

COPY . .
# no need since we have reference volume point
# COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]
